from pypdf import PdfReader, PdfWriter

I=(int(input("entrez le nombre de fichier fesant l'objet d'une extraction : ")))

if I ==1:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)


if I ==2:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)

if I ==3:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)

if I ==4:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)


if I ==5:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)


if I ==6:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)

if I ==7:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)
	u=input("Input bisbis avec .pdf : ")
	reader = PdfReader(u)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	k=input("Output avec .pdf : ")
	writer.write(k)


if I ==8:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)
	u=input("Input bisbis avec .pdf : ")
	reader = PdfReader(u)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	k=input("Output avec .pdf : ")
	writer.write(k)
	q=input("Input bisbis avec .pdf : ")
	reader = PdfReader(q)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	d=input("Output avec .pdf : ")
	writer.write(d)

if I ==8:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)
	u=input("Input bisbis avec .pdf : ")
	reader = PdfReader(u)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	k=input("Output avec .pdf : ")
	writer.write(k)
	q=input("Input bisbis avec .pdf : ")
	reader = PdfReader(q)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	d=input("Output avec .pdf : ")
	writer.write(d)


if I ==9:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)
	u=input("Input bisbis avec .pdf : ")
	reader = PdfReader(u)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	k=input("Output avec .pdf : ")
	writer.write(k)
	q=input("Input bisbis avec .pdf : ")
	reader = PdfReader(q)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	d=input("Output avec .pdf : ")
	writer.write(d)
	w=input("Input bisbis avec .pdf : ")
	reader = PdfReader(w)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	x=input("Output avec .pdf : ")
	writer.write(x)


if I ==10:
	t=input("Input avec .pdf : ")
	reader = PdfReader(t)
	o=(int(input("entrez le numero (+1) de la page à extraire : ")))
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	u=input("Output avec .pdf : ")
	writer.write(u)
	s=input("Input bis avec .pdf : ")
	reader = PdfReader(s)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	i=input("Output avec .pdf : ")
	writer.write(i)
	a=input("Input ibis avec .pdf : ")
	reader = PdfReader(a)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	z=input("Output avec .pdf : ")
	writer.write(z)
	b=input("Input biis avec .pdf : ")
	reader = PdfReader(b)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	c=input("Output avec .pdf : ")
	writer.write(c)
	e=input("Input isib avec .pdf : ")
	reader = PdfReader(e)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	r=input("Output avec .pdf : ")
	writer.write(r)
	t=input("Input isbis avec .pdf : ")
	reader = PdfReader(t)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	y=input("Output avec .pdf : ")
	writer.write(y)
	u=input("Input bisbis avec .pdf : ")
	reader = PdfReader(u)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	k=input("Output avec .pdf : ")
	writer.write(k)
	q=input("Input bisbis avec .pdf : ")
	reader = PdfReader(q)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	d=input("Output avec .pdf : ")
	writer.write(d)
	w=input("Input bisbis avec .pdf : ")
	reader = PdfReader(w)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	x=input("Output avec .pdf : ")
	writer.write(x)
	v=input("Input bisbis avec .pdf : ")
	reader = PdfReader(v)
	p = reader.pages[o]
	writer = PdfWriter()
	writer.add_page(p)
	n=input("Output avec .pdf : ")
	writer.write(n)